In [1]:
!pip install dill

Collecting dill
  Downloading dill-0.3.9-py3-none-any.whl.metadata (10 kB)
Downloading dill-0.3.9-py3-none-any.whl (119 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.4/119.4 kB 2.5 MB/s eta 0:00:00
Installing collected packages: dill
Successfully installed dill-0.3.9

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import os

In [4]:
os.chdir('/content/drive/My Drive/NLP-Letters-V2/notebooks/')

In [61]:
df = pd.read_csv('../data/conceptx_data/clusters-100.txt', sep='\|\|\|')
df.columns = ['Word', 'WordID', 'SentID', 'TokenID', 'ClusterID']

<ipython-input-61-ea21115f7d6c>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv('../data/conceptx_data/clusters-100.txt', sep='\|\|\|')

In [99]:
df[df['ClusterID'] == 87][:50]

             Word WordID  SentID  TokenID  ClusterID
14273       while      1       3        0         87
14274           ’      1       3        2         87
14275           —      1       3       31         87
14276           —      2       3       38         87
14277       alice      1      11       18         87
14278        what      1      13       18         87
14279          to      9      13       26         87
14280         and     14      14        3         87
14281           ’      2      30       30         87
14282           ’      3      38        9         87
14283   personnel      1      39       21         87
14284           ’      4      40        7         87
14285        know      1      48        1         87
14286           ]      1      48       19         87
14287           ’      5      50       15         87
14288           “      1      51       10         87
14289           ”      1      51       16         87
14290           ’      6      58       12         87
14291           '      1      70       20         87
14292           ’      7      70       21         87
14293           "      1      72       10         87
14294           ¬      1      72       11         87
14295           ¢      1      72       12         87
14296      simply      1      77        8         87
14297        just      2      77       11         87
14298           “      2      77       12         87
14299        gets      1      77       13         87
14300           ”      2      77       15         87
14301          or      5      79        5         87
14302         did      1      82        3         87
14303        june      1      82        9         87
14304          27      1      82       10         87
14305        long      2      82       12         87
14306      number      1      82       13         87
14307        july      1      82       14         87
14308          22      1      82       15         87
14309        long      3      82       17         87
14310      number      2      82       18         87
14311     service      4      83        0         87
14312           ’      8      83        8         87
14313         she     21      84        0         87
14314  identifier     27      90        8         87
14315           1      2      95        1         87
14316       alice      2      95       15         87
14317           ’      9     101       10         87
14318     project      1     102       23         87
14319         far      2     107        1         87
14320           ’     10     108        1         87
14321           ’     11     111        1         87
14322           ’     12     117        4         87

In [96]:
df[df['Word'] == 'he']

      Word WordID  SentID  TokenID  ClusterID
10282   he      1       3       39         20
10284   he      2       5        4         20
10286   he      3       6       19         20
10288   he      5      13        6         20
10291   he      8      18        5         20
...    ...    ...     ...      ...        ...
11799   he    291     982        0         45
14486   he    130     451        0         87
14540   he    162     605        0         87
14636   he    260     877       16         87
19870   he     40     118       23         11

[292 rows x 5 columns]