In [ ]:
import pandas as pd
import os
import re
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
os.chdir('/content/drive/My Drive/NLP-Letters-V2/notebooks/')
df1 = pd.read_csv('../data/letters_2021.csv')
df2 = pd.read_csv('../data/sentence_sets_trimmed.csv', encoding='mac-roman')
df2 = df2[df2['full_text_tokens'] > 10]

# First Dataset

In [ ]:
identifier_pattern = r'(?:^|\b|[^\w\s]+)(first_name|identifier|last_name|middle_name)(?:\b|[^\w\s]+|$)'
pronoun_pattern = r"(?:^|\b|[^\w\s]+)(he|she|him|himself|herself|her|his|hers|he’s|she’s|he's|she's)(?:\b|[^\w\s]+|$)"

In [ ]:
def classify_sentence(sentence):
    if re.search(identifier_pattern, sentence, re.IGNORECASE):
        return 's1'
    elif re.search(pronoun_pattern, sentence, re.IGNORECASE):
        return 's2'
    else:
        return 's3'

In [ ]:
df1['sentences'] = df1['LETTERTEXT'].apply(nltk.sent_tokenize)

In [ ]:
df1['s1'] = None
df1['s2'] = None
df1['s3'] = None
df1['s1_s2'] = None

for idx, row in df1.iterrows():
    s1_sentences = []
    s2_sentences = []
    s3_sentences = []
    s1_s2_sentences = []

    for sentence in row['sentences']:
        category = classify_sentence(sentence)
        if category == 's1':
            s1_sentences.append(sentence)
            s1_s2_sentences.append(sentence)
        elif category == 's2':
            s2_sentences.append(sentence)
            s1_s2_sentences.append(sentence)
        else:
            s3_sentences.append(sentence)

    df1.at[idx, 's1'] = ' '.join(s1_sentences)
    df1.at[idx, 's2'] = ' '.join(s2_sentences)
    df1.at[idx, 's3'] = ' '.join(s3_sentences)
    df1.at[idx, 's1_s2'] = ' '.join(s1_s2_sentences)

In [ ]:
df1['full_text'] = df1['LETTERTEXT'].astype(str)
df1['full_text'] = df1['full_text'].str.lower()
df1['s1'] = df1['s1'].str.lower()
df1['s2'] = df1['s2'].str.lower()
df1['s3'] = df1['s3'].str.lower()
df1['s1_s2'] = df1['s1_s2'].str.lower()

In [ ]:
df1

,MD5_ID,YEAR,LETTERNUM,LETTER_GENDER,LETTERTEXT,GENDERLESS_TEXT,sentences,s1,s2,s3,s1_s2,full_text
0,933e79d01a4aad7671a1120d6b5fddb5,2021,1,F,It is my pleasure to write a letter of recomme...,It is my pleasure to write a letter of recomme...,[It is my pleasure to write a letter of recomm...,it is my pleasure to write a letter of recomme...,her pleasing personality and sincere dedicatio...,,it is my pleasure to write a letter of recomme...,it is my pleasure to write a letter of recomme...
1,933e79d01a4aad7671a1120d6b5fddb5,2021,2,F,I am pleased to highly recommend IDENTIFIER fo...,I am pleased to highly recommend IDENTIFIER fo...,[I am pleased to highly recommend IDENTIFIER f...,i am pleased to highly recommend identifier fo...,she is a quick learner who grasped the materia...,i have worked at jamaica hospital medical cent...,i am pleased to highly recommend identifier fo...,i am pleased to highly recommend identifier fo...
2,933e79d01a4aad7671a1120d6b5fddb5,2021,3,F,I am writing this letter in support of IDENTIF...,I am writing this letter in support of IDENTIF...,[I am writing this letter in support of IDENTI...,i am writing this letter in support of identif...,,,i am writing this letter in support of identif...,i am writing this letter in support of identif...
3,458e7ee7e1ba439d294123d18217ccc6,2021,1,F,IDENTIFIER IDENTIFIER recently completed an an...,IDENTIFIER IDENTIFIER recently completed an an...,[IDENTIFIER IDENTIFIER recently completed an a...,identifier identifier recently completed an an...,i have found her to always be professional and...,"if you have any questions, please do not hesit...",identifier identifier recently completed an an...,identifier identifier recently completed an an...
4,458e7ee7e1ba439d294123d18217ccc6,2021,2,F,It is my pleasure to recommend Dr. IDENTIFIER ...,It is my pleasure to recommend Dr. IDENTIFIER ...,[It is my pleasure to recommend Dr. IDENTIFIER...,it is my pleasure to recommend dr. identifier ...,although it was the first rotation of her tran...,,it is my pleasure to recommend dr. identifier ...,it is my pleasure to recommend dr. identifier ...
...,...,...,...,...,...,...,...,...,...,...,...,...
5702,4948148cd84320b7c3ca41743f860465,2021,3,F,It is with great pleasure that I recommend med...,It is with great pleasure that I recommend med...,[It is with great pleasure that I recommend me...,it is with great pleasure that i recommend med...,her performance was truly outstanding. she was...,i often assign topics to present to the medica...,it is with great pleasure that i recommend med...,it is with great pleasure that i recommend med...
5703,4948148cd84320b7c3ca41743f860465,2021,4,F,IDENTIFIER is an enthusiastic young woman who ...,IDENTIFIER is an enthusiastic young woman who ...,[IDENTIFIER is an enthusiastic young woman who...,identifier is an enthusiastic young woman who ...,she was referred to me due to her interest in ...,"under my mentorship, we planned our publicatio...",identifier is an enthusiastic young woman who ...,identifier is an enthusiastic young woman who ...
5704,003f1558964ebd71b9dbba552a815b90,2021,1,F,A pleasure to work with” ERAS Application Seas...,A pleasure to work with” ERAS Application Seas...,[A pleasure to work with” ERAS Application Sea...,a pleasure to work with” eras application seas...,"of note, she has already accomplished several ...",these include helping in the conceptualization...,a pleasure to work with” eras application seas...,a pleasure to work with” eras application seas...
5705,003f1558964ebd71b9dbba552a815b90,2021,2,F,It is with great pleasure that I write a lette...,It is with great pleasure that I write a lette...,[It is with great pleasure that I write a lett...,it is with great pleasure that i write a lette...,she has a left a very strong impression during...,"if you have any further questions, please don’...",it is with great pleasure that i write a lette...,it is with great pleasure that i write a lette...
5706,003f1558964ebd71b9dbba552a815b90,2021,3,F,[POSSIBLE_IDENTIFIER: IDENTIFIER AAMC ID: IDEN...,[POSSIBLE_IDENTIFIER: IDENTIFIER AAMC ID: IDEN...,[[POSSIBLE_IDENTIFIER: IDENTIFIER AAMC ID: IDE...,[possible_identifier: identifier aamc id: iden...,"she is detail oriented, an outstanding problem...",,[possible_identifier: identifier aamc id: iden...,[possible_identifier: identifier aamc id: iden...

# Second Dataset

In [ ]:
df2['sentences'] = df2['TEXT'].apply(nltk.sent_tokenize)

In [ ]:
df2['s1'] = None
df2['s2'] = None
df2['s3'] = None
df2['s1_s2'] = None

for idx, row in df2.iterrows():
    s1_sentences = []
    s2_sentences = []
    s3_sentences = []
    s1_s2_sentences = []

    for sentence in row['sentences']:
        category = classify_sentence(sentence)
        if category == 's1':
            s1_sentences.append(sentence)
            s1_s2_sentences.append(sentence)
        elif category == 's2':
            s2_sentences.append(sentence)
            s1_s2_sentences.append(sentence)
        else:
            s3_sentences.append(sentence)

    df2.at[idx, 's1'] = ' '.join(s1_sentences)
    df2.at[idx, 's2'] = ' '.join(s2_sentences)
    df2.at[idx, 's3'] = ' '.join(s3_sentences)
    df2.at[idx, 's1_s2'] = ' '.join(s1_s2_sentences)

In [ ]:
df2['full_text'] = df2['TEXT'].astype(str)
df2['full_text'] = df2['full_text'].str.lower()
df2['s1'] = df2['s1'].str.lower()
df2['s2'] = df2['s2'].str.lower()
df2['s3'] = df2['s3'].str.lower()
df2['s1_s2'] = df2['s1_s2'].str.lower()

In [ ]:
df2

,applicant_id,document,writer_gender,letter_type,applicant_gender,applicant_identify,applicant_identify_group,standardized_lor,us_canadian,usmle_1,usmle_2,applicants_writers,TEXT,full_text,s1,s2,s1_s2,s3,full_text_tokens,sentences
0,male_3090,sentence_sets.csv.4358,female,lor,male,white,white,1,1,197,225,male_female,this letter serves as the department of medici...,this letter serves as the department of medici...,first_name last_name . last_name waived his ri...,"his presentations were detailed oriented , wri...",first_name last_name . last_name waived his ri...,this letter serves as the department of medici...,526,[this letter serves as the department of medic...
1,female_267,sentence_sets.csv.4301,male,lor,female,asian - chinese,asian,1,1,203,227,female_male,this letter is written in support of FIRST_NAM...,this letter is written in support of first_nam...,this letter is written in support of first_nam...,"by milestone assessment , her areas of strengt...",this letter is written in support of first_nam...,our residents rotate in both inpatient and amb...,447,[this letter is written in support of FIRST_NA...
2,male_1004,sentence_sets.csv.179,male,lor,male,"hispanic, latino, or of spanish origin - mexic...",hispanic_latino_spanish,1,1,206,237,male_male,comments from anesthesiology rotations : ‚Äú F...,comments from anesthesiology rotations : ‚äú f...,comments from anesthesiology rotations : ‚äú f...,he had excellent questions to showed his since...,comments from anesthesiology rotations : ‚äú f...,"‚äù ‚äú works hard , always looking for ways t...",365,[comments from anesthesiology rotations : ‚Äú ...
3,female_147,sentence_sets.csv.3846,male,lor,female,"hispanic, latino, or of spanish origin - other...",hispanic_latino_spanish,1,1,206,217,female_male,long number ms LAST_NAME had originally planne...,long number ms last_name had originally planne...,long number ms last_name had originally planne...,"she took full advantage of the opportunity , f...",long number ms last_name had originally planne...,( 2 ) | am not aware of any areas that require...,346,[long number ms LAST_NAME had originally plann...
4,male_381,sentence_sets.csv.6,female,lor,male,black or african american - african american|b...,black or african american,1,1,210,225,male_female,‚Äú i think [ FIRST_NAME ] would be an asset t...,‚äú i think [ first_name ] would be an asset t...,‚äú i think [ first_name ] would be an asset t...,he's someone | look forward to speaking with a...,‚äú i think [ first_name ] would be an asset t...,ucsd would be fortunate to get to keep this fu...,512,[‚Äú i think [ FIRST_NAME ] would be an asset ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3280,female_29,sentence_sets.csv.3354,male,chair,female,asian - chinese,asian,0,1,273,261,female_male,it is with pleasure that i recommend FIRST_NAM...,it is with pleasure that i recommend first_nam...,it is with pleasure that i recommend first_nam...,she was interested during rounds in all patien...,it is with pleasure that i recommend first_nam...,the medical icu rotation is a demanding rotati...,199,[it is with pleasure that i recommend FIRST_NA...
3281,female_292,sentence_sets.csv.4395,female,lor,female,asian - chinese,asian,0,1,273,261,female_female,we are very pleased to write this letter based...,we are very pleased to write this letter based...,we are very pleased to write this letter based...,she has waived her right to see this letter . ...,we are very pleased to write this letter based...,ms . ms . . . . . . . and was always seeking f...,820,[we are very pleased to write this letter base...
3282,male_651,sentence_sets.csv.1013,male,lor,male,asian - chinese,asian,0,1,274,277,male_male,| am writing this letter of recommendation for...,| am writing this letter of recommendation for...,| am writing this letter of recommendation for...,during his four weeks he rotated through traum...,| am writing this letter of recommendation for...,please do not hesitate to contact me if you ha...,288,[| am writing this letter of recommendation fo...
3283,male_1930,sentence_sets.csv.2528,male,lor,male,asian - chinese,asian,0,1,274,277,male_male,it is my pleasure to write FIRST_NAME support ...,it is my pleasure to write first_name support ...,it is my pleasure to write first_name support ...,the fellow he was working with and i were extr...,it is my pleasure to write first_name support ...,i am writing this letter to give my highest po...,551,[it is my pleasure to write FIRST_NAME support...
3284,male_2844,sentence_sets.csv.4006,male,lor,male,asian - chinese,asian,0,1,274,277,male_male,please accept my strongest recommendation for ...,please accept my strongest recommendation for ...,please accept my strongest recommendation for ...,"he was extremely motivated , hardworking , and...",please accept my strongest recommendation for ...,"if you have any questions , please do not hesi...",247,[please accept my strongest recommendation for...

# Combine Datasets

In [ ]:
df1 = df1[['s1_s2', 'full_text', 'LETTER_GENDER']]
df1 = df1.rename(columns={'LETTER_GENDER':'label'})
df2 = df2[['s1_s2', 'full_text', 'applicant_gender']]
df2 = df2.rename(columns={'applicant_gender':'label'})

In [ ]:
df = pd.concat([df1, df2], ignore_index=True)

In [ ]:
gender_label_mapping = {
    'F':0,
    'female':0,
    'M':1,
    'male':1
}

In [ ]:
df['label'] = df['label'].replace(gender_label_mapping)

<ipython-input-37-cc45885305bc>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['label'] = df['label'].replace(gender_label_mapping)

# Create Dataframe for Word2Vec Experiments

In [ ]:
letters = df['s1_s2'].astype(str)
sentences = [sent_tokenize(letter) for letter in letters]
sentences = pd.concat([df, pd.Series(sentences, name='sentences')], axis=1)
sentences = sentences[['sentences']].explode('sentences')
df_sentences = pd.merge(df, sentences, left_index=True, right_index=True)

In [ ]:
# df_sentences.to_csv('../data/df_sentences_with_gender.csv', index=False)

# Take subset of 500 recommendation letters from each label

In [ ]:
df_label0 = df[df['label'] == 0].sample(n=500, random_state=42)
df_label1 = df[df['label'] == 1].sample(n=500, random_state=42)

# Combine them
df_balanced = pd.concat([df_label0, df_label1])

# Shuffle the dataset
df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

In [ ]:
letters = df_balanced['s1_s2'].astype(str)
sentences = [sent_tokenize(letter) for letter in letters]
sentences = pd.concat([df_balanced, pd.Series(sentences, name='sentences')], axis=1)
sentences = sentences[['sentences']].explode('sentences')
df_sentences = pd.merge(df_balanced, sentences, left_index=True, right_index=True)

# Take subset of 500 sentences from each label

In [ ]:
df_label0_1000 = df_sentences[df_sentences['label'] == 0].sample(n=500, random_state=42)
df_label1_1000 = df_sentences[df_sentences['label'] == 1].sample(n=500, random_state=42)

# Combine them
df_balanced_1000 = pd.concat([df_label0_1000, df_label1_1000])

# Shuffle the dataset
df_balanced_1000 = df_balanced_1000.sample(frac=1, random_state=42).reset_index(drop=True)

In [ ]:
sentences = df_balanced_1000['sentences'].tolist()

In [ ]:
# with open("../data/sentences.txt", "w") as f:
#     f.writelines(sentence + "\n" for sentence in sentences)